### ISSUE TITLE
regularization for FM

### ISSUE THREAD

**Issue by Sandy4321** [takuti/flurs#1]
data matrix usually spars, so may you clarify if you use regularization
Thanks

**Comment by Sandy4321** [comment]
video 30:07 regularization to use with SGD for FM  
https://www.youtube.com/watch?v=LV4JLTIZxNU

**Comment by takuti** [comment]
Hi, I cannot understand what you expect. FM already uses L2 regularization [here](https://github.com/takuti/flurs/blob/master/flurs/model/fm.py#L50-L65). Do you have any suggestions related to the code?

**Comment by Sandy4321** [comment]
yes it is my question, so you do have L2 regularization <- very good. May you clarify , 
1 
do you have L1 regularization?  
2
do you have regularization not only for regression coefficients but for satisfaction  parameters V  as well?
3
May you share some code example for simple recommendation system from 0 to end
for example movies recommendations?

**Comment by takuti** [comment]
1. No. The implementation simply follows formulation in the FM paper which only utilizes L2 regularization.
2. Yes, as the name of variable `l2_reg_V` suggests.
3. Thank you for your suggestion. I'll prepare it as soon as I can.
