### ISSUE TITLE
error installing on windows computer and python 3  

### ISSUE THREAD

**Issue by Sandy4321** [takuti/flurs#4]
Please help how install on Windows computer and Python 3

details about python installation are:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
 
D:\code>python
Python 3.5.4 |Anaconda custom (64-bit)| (default, Aug 14 2017, 13:41:13) [MSC v.
1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

error message is 
D:\code>pip install flurs
Collecting flurs
  Downloading flurs-0.0.2.tar.gz
Requirement already satisfied: numpy in c:\anaconda3\lib\site-packages (from flu
rs)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from flu
rs)
Requirement already satisfied: scikit_learn in c:\anaconda3\lib\site-packages (f
rom flurs)
Collecting mmh3 (from flurs)
  Downloading mmh3-2.5.1.tar.gz
Building wheels for collected packages: flurs, mmh3
  Running setup.py bdist_wheel for flurs ... done
  Stored in directory: C:\Users\AppData\Local\pip\Cache\wheels\4d\57\63\2
79a1b015f85bafe80a65708340abde3313d0ed3a76e68beb9
  Running setup.py bdist_wheel for mmh3 ... error
  Complete output from command c:\anaconda3\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-build-stf4mwne\
\mmh3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().repla
ce('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
C:\Users\AppData\Local\Temp\tmpme3fog09pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\anaconda3\include -Ic:\anacond
a3\include /EHsc /Tpmmh3module.cpp /Fobuild\temp.win-amd64-3.5\Release\mmh3modul
e.obj
  error: command 'cl.exe' failed: No such file or directory
 
  ----------------------------------------
  Failed building wheel for mmh3
  Running setup.py clean for mmh3
Successfully built flurs
Failed to build mmh3
Installing collected packages: mmh3, flurs
  Running setup.py install for mmh3 ... error
    Complete output from command c:\anaconda3\python.exe -u -c "import setuptool
s, tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-build-stf4mwn
e\\mmh3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().rep
lace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --re
cord C:\Users\AppData\Local\Temp\pip-4_zt8393-record\install-record.txt -
-single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\anaconda3\include -Ic:\anaco
nda3\include /EHsc /Tpmmh3module.cpp /Fobuild\temp.win-amd64-3.5\Release\mmh3mod
ule.obj
    error: command 'cl.exe' failed: No such file or directory
 
    ----------------------------------------
Command "c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:
\\Users\\AppData\\Local\\Temp\\pip-build-stf4mwne\\mmh3\\setup.py';f=get
attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo
se();exec(compile(code, __file__, 'exec'))" install --record C:\Users\App
Data\Local\Temp\pip-4_zt8393-record\install-record.txt --single-version-external
ly-managed --compile" failed with error code 1 in C:\Users\AppData\Local\
Temp\pip-build-stf4mwne\mmh3\
 
D:\code>

**Comment by takuti** [comment]
In fact, since I have never tested this package on Windows, I cannot fully realize why compilation has been failed. 

However, you first try to google the error message `error: command 'cl.exe' failed: No such file or directory`; I found many same issues, and the reason is probably in your PATH setting as discussed in: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

BTW, in order to test how FluRS works on Windows, I will setup CI for Windows environment in #5.
