### ISSUE TITLE
updated are not on pip for appveyor  and etc

### ISSUE THREAD

**Issue by Sandy4321** [takuti/flurs#7]
you added something like 
https://github.com/takuti/flurs/tree/master/appveyor
but last pip update is on 2017-08-31 version flurs-0.0.2.tar.gz (md5)
may you update please pip instalaltion
by the way what this  appveyor doing for Windows OS?

**Comment by takuti** [comment]
See https://github.com/takuti/flurs/blob/master/appveyor.yml

AppVeyer gets source from this repo and tries to build and test the latest source code on Windows environment. Search on google for further basic knowledge which is not directly related to FluRS code.

It should be noted that, as I mentioned in #7, `pip install flurs` (install from PyPI; latest version is  2017-08-31 version flurs-0.0.2.tar.gz) and `pip install .` (directly install from the latest code on this repo) are different.
